import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";

export interface CodexOptions {
  model: string;
  /** true → ChatGPT subscription (requires_openai_auth, no key). false → use apiKey. */
  subscription: boolean;
  /** OpenAI key (only when subscription is false); "" → env OPENAI_API_KEY. */
  apiKey: string;
}

export interface ProxyConfigOptions {
  /** When set, paritok.yaml enables the codex block so `paritok up` writes ~/.codex/config.toml. */
  codex?: CodexOptions;
}

/**
 * Writes a minimal paritok.yaml into the extension's global storage and returns
 * its path. This is the config the spawned `paritok up` process reads.
 *
 * We set only what the hosted (GPU-server) backend needs plus, optionally, the
 * `codex:` block — because paritok itself writes ~/.codex/config.toml from that
 * block on startup. Everything else falls back to paritok's own defaults, so we
 * never fossilize the engine's tuning (min_tokens, history, tool_discovery, ...)
 * into the extension — the Python side owns all of that.
 */
export async function writeProxyConfig(
  context: vscode.ExtensionContext,
  apiKey: string,
  opts: ProxyConfigOptions = {}
): Promise<string> {
  const dir = context.globalStorageUri.fsPath;
  fs.mkdirSync(dir, { recursive: true });
  const cfgPath = path.join(dir, "paritok.yaml");

  const q = (s: string) => s.replace(/"/g, '\\"');
  const lines = [
    "# Generated by the Paritok VS Code extension. Do not edit by hand —",
    "# it is rewritten from the extension's settings + stored keys.",
    "use_gpu_server: true",
    "gpu_server:",
    "  base_url: https://www.paritok.com/api",
    "  model: paritok-4b-v1",
    `  api_key: "${q(apiKey)}"`,
    "  timeout: 60.0",
  ];

  // Codex routing: paritok writes ~/.codex/config.toml when codex.enabled is true.
  if (opts.codex) {
    lines.push(
      "codex:",
      "  enabled: true",
      `  model: "${q(opts.codex.model)}"`,
      `  subscription: ${opts.codex.subscription ? "true" : "false"}`,
      `  api_key: "${q(opts.codex.apiKey)}"`
    );
  } else {
    lines.push("codex:", "  enabled: false");
  }
  lines.push("");

  fs.writeFileSync(cfgPath, lines.join("\n"), "utf8");
  return cfgPath;
}
