import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";

/**
 * Writes a minimal paritok.yaml into the extension's global storage and returns
 * its path. This is the config the spawned `paritok up` process reads.
 *
 * We only set the two things the hosted (GPU-server) backend needs: the switch
 * and the API key. Everything else falls back to paritok's own defaults, so we
 * never fossilize the engine's tuning (min_tokens, history, tool_discovery, ...)
 * into the extension — the Python side owns all of that.
 */
export async function writeProxyConfig(
  context: vscode.ExtensionContext,
  apiKey: string
): Promise<string> {
  const dir = context.globalStorageUri.fsPath;
  fs.mkdirSync(dir, { recursive: true });
  const cfgPath = path.join(dir, "paritok.yaml");

  // Note: YAML written by hand (no dependency). Only trivial scalar values, so
  // this is safe. The api_key is quoted to survive any special characters.
  const safeKey = apiKey.replace(/"/g, '\\"');
  const yaml = [
    "# Generated by the Paritok VS Code extension. Do not edit by hand —",
    "# it is rewritten from the extension's settings + stored API key.",
    "use_gpu_server: true",
    "gpu_server:",
    "  base_url: https://www.paritok.com/api",
    "  model: paritok-4b-v1",
    `  api_key: "${safeKey}"`,
    "  timeout: 60.0",
    "",
  ].join("\n");

  fs.writeFileSync(cfgPath, yaml, "utf8");
  return cfgPath;
}
